apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootcamp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/obianuju-linda/DevOps-bootcamp-App-stack.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: bootcampt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
